<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>bootcamp Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>rpbautistajr@yahoo.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9e523226-fadd-44cb-b37b-ca904cc04cd0</testSuiteGuid>
   <testCaseLink>
      <guid>6fd6b3ab-3dc6-4418-8b92-2a598f7581d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/browserFunctions</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>dad695a1-0253-4757-b157-4949cd125b76</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/checkboxFunctions</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b64d793a-7ad7-449e-b686-8c9da6c22265</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/comboBoxFunctions</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2bfec76c-fd68-45ed-a612-8abc7f62ed4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/takeScreenshotFunctions</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0ed7833-7357-4df6-ac87-3bf8a19c903f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d336700-9dc2-437d-9075-95b89a5b20e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4222f5bd-ad8d-4177-9acb-4d1f6b05d499</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f78ae244-3efd-4f88-a85f-ebdd4533af2f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e116349-275c-414e-a599-a8f8e2763d19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/textBoxAndClickFunctions</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e7997d65-f8e9-4aeb-b882-d7e6da8e7b8e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/explicitWaitFunctions</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>142feaf0-ee86-4aaa-8d38-148533e10679</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68c13ef5-505f-4e0d-a68d-550ca9556b21</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a46bcb6a-b23b-4f1f-a9c7-4a304d7fb97b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebf1b340-0528-40b7-8c8c-cda62e80b809</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bf6c6522-fc6c-4abd-a382-cada1589359e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/multipleBrowserWindowHandling</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34772233-73a1-486c-a366-9a1c0f18e58d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9368e57d-3624-4ee3-9396-1012294283a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e3eb891-5f1a-4f72-9e0e-2139ab0cef47</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ed166b5-35e1-4c2a-a75d-1df240c43855</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/htmlFrames</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34772233-73a1-486c-a366-9a1c0f18e58d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9368e57d-3624-4ee3-9396-1012294283a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e3eb891-5f1a-4f72-9e0e-2139ab0cef47</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c871d66-aa94-4657-aada-547cb85e5ed7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/javascriptPopUpFunctions/javascriptAlertFunctions</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4cc78df-c03b-4a18-9d1c-4bf667bf3ac4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d67363ed-2cc4-4fdb-b234-16480c5fc8b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/javascriptPopUpFunctions/javascriptConfirmFunctions</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78c01169-f58b-41ba-8658-1f2b06d52b01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0cadae4-f90a-4cde-adcd-28b262e334b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/javascriptPopUpFunctions/javascriptPromptFunctions</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f994f552-4a19-40a6-a0f3-495f4cec928b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f27c535-16b3-4645-b0bb-e04b992b81d2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>84a67a2e-e306-4854-af2d-f9dbe9e2da64</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mouse Actions/doubeClickFunctions</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7455116-8013-4c56-9c3e-513aef5f21c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>105e4f3a-fd0b-4040-bcc4-2dfafc112d87</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mouse Actions/dragAndDropFunctions</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab04db98-08bc-4f0b-b45f-3b9536d822b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9543162-48a9-4f10-8b93-4473b82435a6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/focusFunctions</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ce2dc70-01a0-4cf2-a01d-102bd4948ece</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d5dacf6-e950-48ef-bc76-834b1a85aeb0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mouse Actions/mouseHoverFunctions</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f877da41-a89b-4083-a6b7-6ccf42d0a51d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9576fe83-abcc-49f0-b257-fa5a5aa84152</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mouse Actions/autoSuggestListFunctions</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf651d2b-bb25-4508-8bf8-46f2c9d5e34c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c40c42f-2566-481f-8c63-7dcc913a4138</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0f16ebd-a270-40b0-94d8-364e41a3d661</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/browserFunctions</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f6096d4f-f703-4753-b7d0-11b1042edf9b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/customKeyword/closeBrowserCustomKeyword</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>91d04b94-7d84-4b32-bd3f-2afc7b9829b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/parameterizedKeyword/parameterizedOpenBrowser</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba63b32e-cdf1-434c-877d-1df821feb804</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c659bcba-ea4a-4868-9fc7-0c9e9323b97a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/customKeyword/fileUpload</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>fa9e58de-120f-4b54-b1ef-31c8e76b1fa0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/callTestCase/mainTest/TC001-Accessing Dashboard</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
